{
    'name': 'Ship Report',
    'version': '17.0.1.0.0',
    'category': 'Shipping',
    'summary': 'Shipping Job Reports',
    'depends': ["base",'shipping_proxy','report_xlsx',
    ],
    'data': [
        "security/ir.model.access.csv",
        "views/ship_report_menu.xml",
        "report/ship_report_report.xml",
        "views/ship_report_wizard_view.xml",
        'views/ship_report_html_templates.xml',
        "report/ship_report_actions.xml",
        "report/ship_report_detail_qweb.xml",
        "report/ship_report_summary_qweb.xml",
        "report/ship_report_xlsx.xml",
    ],
    'installable': True,
}
