{
    'name': 'Shipping Report',
    'version': '17.0.1.0.0',
    'summary': 'Centralized Shipping Reports Module',
    'description': """
        Shipping Reporting Module- Future reports""",
    'category': 'Reporting',
    'author': 'Your Company',
    'depends': ['base', 'web', 'mail', 'account', 'purchase', 'report_xlsx', 'shipping_proxy', ],
    'data': [
        'security/ir.model.access.csv',
        'wizard/jobprofit_by_charge_wizard_view.xml',
        'wizard/sea_consol_wizard_view.xml',
        'wizard/ship_report_wizard.xml',
        'wizard/work_volume_wizard_view.xml',
        'wizard/unbilled_jobs_wizard_view.xml',
        'report/sea_consol_report_xlsx.xml',
        'report/ship_report_qweb.xml',
        'report/ship_report_xlsx.xml',
        'report/work_volume_template.xml',
        'report/unbilled_jobs_xlsx.xml',
        'views/jobprofit_menu.xml',
        'views/sea_consol_menu.xml',
        'views/sea_export_action.xml',
        'views/sea_export_menu.xml',
        'views/ship_report_actions.xml',
        'views/ship_report_menu.xml',
        'views/unbilled_views.xml',

        "wizard/shipment_revenue_wizard_view.xml",
        "wizard/shipment_status_wizard_view.xml",
        "wizard/client_analysis_wizard_view.xml",
        "wizard/shipment_consolidation_wizard_view.xml",
        "wizard/job_count_summary_wizard_view.xml",
        "wizard/shipment_listing_wizard_view.xml",
        "wizard/ship_quote_vs_transaction_wizard_view.xml",
        "report/shipment_revenue_xlsx.xml",
        "report/shipment_status_xlsx.xml",
        "report/client_analysis_xlsx.xml",
        "report/shipment_consolidation_xlsx.xml",
        "report/job_count_summary_xlsx.xml",
        "report/job_count_summary_pdf_action.xml",
        "report/shipment_listing_xlsx_action.xml",
        "report/ship_quote_transaction_xlsx.xml",
        "report/job_count_summary_template.xml",
        "report/shipment_listing_preview.xml",
        "report/shipment_listing_pdf_template.xml",
        "report/shipment_listing_pdf_action.xml",
        "report/shipment_listing_report.xml",
        "views/menu.xml",
    ],
    'installable': True,
    'application': True,
}
